name: Update SideStore Source
on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download All IPAs from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 현재 릴리스에 포함된 모든 .ipa 파일을 다운로드
          gh release download ${{ github.event.release.tag_name }} --pattern "*.ipa"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Script
        env:
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: python update_source.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add "NightFox Repository.json"
          git commit -m "Update source for 40 apps" || echo "No changes"
          git push
